"""empty message

Revision ID: 17e1a0fa3e4d
Revises: 12668e5ab6ea
Create Date: 2014-08-21 16:37:07.595450

"""

# revision identifiers, used by Alembic.
revision = '17e1a0fa3e4d'
down_revision = '12668e5ab6ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
