"""empty message

Revision ID: 429e3e6d1ea2
Revises: 17e1a0fa3e4d
Create Date: 2014-08-25 15:52:43.268601

"""

# revision identifiers, used by Alembic.
revision = '429e3e6d1ea2'
down_revision = '17e1a0fa3e4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_secret', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_secret')
    ### end Alembic commands ###
